# This is a basic workflow to help you get started with Actions

name: Increment Version

# 実行されるタイミング
on:
  # `main`にPRが作成された or PRにラベルが付けられた
  pull_request:
    branches: 
      - main
    types:
      - opened
      - labeled

# 実行内容
jobs:
  increment_version:
    name: バージョン変更

    runs-on: ubuntu-latest

    steps:
      - name: リポジトリの内容を取得？
        uses: actions/checkout@v2
    
      - name: リリースラベルが付いているか判定
        id: check_release_label
        run: |
          PR_LABELS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" | \
          jq -r '.[].name')
          HAS_RELEASE_LABEL=false
          if [[ $PR_LABELS == *"リリース"* ]]; then
            HAS_RELEASE_LABEL=true
          fi
          echo "has_release_label=$HAS_RELEASE_LABEL" >> $GITHUB_OUTPUT

      - name: PRのタイトルを取得
        id: pr_title
        if: steps.check_release_label.outputs.HAS_RELEASE_LABEL == true
        run: |
          PR_TITLE=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
          jq -r '.title')
          echo 
          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT

      - name: 出力用
        run: |
          echo ${{ steps.check_release_label.outputs.has_release_label }}
          echo ${{ steps.pr_title.outputs.pr_title }}

    # env: # ここで他のステップに共有できるようになるかも？
    #   HAS_RELEASE_LABEL: ${{ steps.check_release_label.outputs.HAS_RELEASE_LABEL }}
    #   PR_TITLE: ${{ steps.pr_title.outputs.PR_TITLE }}

      # - name: Checkout リポジトリ
      #   uses: actions/checkout@v2

      # - name: インクリメントバージョン
      #   if: steps.check_label.outputs.has_label == 'リリース'
      #   run: |
      #     # バージョンをインクリメントするスクリプトをここに書く
      #     # 例: version=$(cat VERSION)
      #     # 新しいバージョンを計算して、ファイルに書き込む
      #     # 例: echo $new_version > VERSION
      #     # git コミットとプッシュ
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git commit -m "Increment version to $new_version"
      #     git push
