# This is a basic workflow to help you get started with Actions

name: Increment Version

# 実行されるタイミング
on:
  # `main`にPRが作成された or PRにラベルが付けられた
  pull_request:
    branches: 
      - main
    types:
      - opened
      - labeled

# 実行内容
jobs:
  increment_version:
    name: バージョン変更
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリの内容を取得？
        uses: actions/checkout@v2

      - name: PRのタイトルを取得
        id: pr_title
        run: |
          PR_TITLE=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
          jq -r '.title')
          echo "PR Title: $PR_TITLE"
    
      # - name: Check if the "リリース" ラベルが付いている
      #   id: check_label
      #   run: echo ::set-output name=has_label::$(echo ${{ github.event.label.name }} | grep 'リリース' || true)
      #   if: github.event_name == 'pull_request' && steps.check_label.outputs.has_label == 'リリース'

      # - name: Checkout リポジトリ
      #   uses: actions/checkout@v2

      # - name: インクリメントバージョン
      #   if: steps.check_label.outputs.has_label == 'リリース'
      #   run: |
      #     # バージョンをインクリメントするスクリプトをここに書く
      #     # 例: version=$(cat VERSION)
      #     # 新しいバージョンを計算して、ファイルに書き込む
      #     # 例: echo $new_version > VERSION
      #     # git コミットとプッシュ
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git commit -m "Increment version to $new_version"
      #     git push
